api = "0.7"

[buildpack]
id = "io.avarteqgmbh.buildpacks.git-ssh"
name = "GIT SSH buildpack"
homepage = "https://github.com/avarteqgmbh/git-ssh-buildpack"

[metadata]
include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
pre-package = "./scripts/build.sh"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
